### ISSUE TITLE
Processing и Android

### ISSUE THREAD

**Issue by waw555** [AlexGyver/GyverTwink#18]
Здравствуйте! 

Не могу экспортировать приложение в apk

Ошибка:

java.lang.NullPointerException: Cannot read the array length because "list" is null
	at processing.app.Library.wrapFiles(Library.java:426)
	at processing.app.Library.getApplicationExports(Library.java:436)
	at processing.mode.android.AndroidBuild.copyImportedLibs(AndroidBuild.java:838)
	at processing.mode.android.AndroidBuild.createAppModule(AndroidBuild.java:475)
	at processing.mode.android.AndroidBuild.createProject(AndroidBuild.java:262)
	at processing.mode.android.AndroidBuild.build(AndroidBuild.java:223)
	at processing.mode.android.AndroidBuild.exportPackage(AndroidBuild.java:793)
	at processing.mode.android.AndroidEditor$19.run(AndroidEditor.java:552)

С чем это может быть связано?

Processing версия 4
Android Studio последней версии, пробовал с разными SDK и 29 и 30

**Comment by GyverLibs** [comment]
Привет, не знаю) я финальный экспорт делал через андроид студию

**Comment by waw555** [comment]
А как вы в Android Studio экспортировали? Одна и та же ошибка у меня, что при экспорте, что при компиляции из Processing.

**Comment by GyverLibs** [comment]
Нажал кнопку и всё ок, проблем не было

**Comment by waw555** [comment]
Можно попросить Вас сделать экспорт и выложить архив для Android Studio, если не сложно. Заранее благодарю.

**Comment by dDenyd** [comment]
> Можно попросить Вас сделать экспорт и выложить архив для Android Studio, если не сложно. Заранее благодарю.

Если ещё актуально: экспортировать проект нужно из "3го процессинга". Но на самом деле это не помощь)) это обречение на муки с андроид студио)) ибо с наскоку там нифига не собирается... Сначала нужно будет побадаться с версиями Gradle и Androd Gradle Plugin...потом убрать дубль в классах из-за ссылок на разные версии библиотек .. и потом только оно, быть может, собирается)))) ну и если нужен экспорт просите на форуме у Алекса, я вам его скину.

**Comment by Tabaqui** [comment]
Для неравнодушных нердов https://github.com/Tabaqui/wink - приложение для ведра экспортированное и пересобраное. В бою нет возможности потестировать пока что
